### ISSUE TITLE
Batch convert to nrrd with peak switching files

### ISSUE THREAD

**Issue by cguillermier** [BWHCNI/OpenMIMS#11]
Autotracking at mass 26 for instance can be CN or C2D...

**Comment by cpoczatek** [comment]
The GUI for autotracking in "batch convert to nrrd" is ambiguous when there is say 2 mass 26 images. Simple fix is to take text field and switch to dropdown list of images.

Zip file with 3 .im fields with one peak switch, 256x256x10 pixels 5X2 masses.
[peak-switching-images.zip](https://github.com/BWHCNI/OpenMIMS/files/293650/peak-switching-images.zip)
