### ISSUE TITLE
Batch convert with bad headers

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#12]
If you try to convert say 10 files and the 5th file has a "bad header" the conversion continues with no warning about file 5. This -should- be a soft fail and the conversion should continue, but there should be a warning / prompt the user if they want to try to fix the problem.

**Comment by cpoczatek** [comment]
Need example image with bad header.

**Comment by cpoczatek** [comment]
This zip has one .im file where the header says 23 planes but the file size implies 24.

[bad_header_im.zip](https://github.com/BWHCNI/OpenMIMS/files/294304/bad_header_im.zip)

**Comment by taylorwrt** [comment]
Collinm,

Got it.

I was wondering if there is a secure place at the Lansdowne street location to keep my bike.    I have a crappy bike I ride in bad weather and I don’t mind locking it up outside, but I have an expensive bike that I prefer to ride, and I don’t like leaving it outside.    

Walter

> On Jun 1, 2016, at 4:15 PM, Collin Poczatek notifications@github.com wrote:
> 
> This zip has one .im file where the header says 23 planes but the file size implies 24.
> 
> bad_header_im.zip https://github.com/BWHCNI/OpenMIMS/files/294304/bad_header_im.zip
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub https://github.com/BWHCNI/OpenMIMS/issues/12#issuecomment-223111079, or mute the thread https://github.com/notifications/unsubscribe/AR0m5PSytDY5ezsaZyH3pFLttJdlJDWQks5qHehRgaJpZM4IrrNg.

Walter Taylor
31 Herrick Rd, Apt 3A
Newton Centre, MA  02459
mobile:  617-803-5874
walter.taylor@icloud.com
