### ISSUE TITLE
Bugs with translation if file compressed

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#16]
To reproduce:
- open any multi plane file
- compress by 2 or more planes
- translate X = +5, Y = +5 with spinners
- translate back to 0, 0 

Original untranslated image (contrast saturated):
![image](https://cloud.githubusercontent.com/assets/14008252/16308601/ac54431c-3933-11e6-8251-22200662783c.png)

Translate +5, +5
![image](https://cloud.githubusercontent.com/assets/14008252/16308661/e531ff9e-3933-11e6-82b4-f20eee45f1bc.png)

Translate back to 0, 0 (should match 1st image)
![image](https://cloud.githubusercontent.com/assets/14008252/16308692/081d748e-3934-11e6-8744-0c75d9c89942.png)

This bug seems to be non-symmetric in X and Y, depends on the order the translations are applied, shows up when using the spinners or the translation tool (red crossed arrows).

**Comment by taylorwrt** [comment]
Fixed.  Most bug 16 changes were in restoreBlock, restoreSlice, 
translateYSpinnerStateChanged, and translateXSpinnerStateChanged.  Key
changes were in adding restoreIndex parameter to call to 
getProcessor.setPixels, and in keeping X and Y translation handling code
separate in the translateXSpinnerStateChanged and 
translateYSpinnerStateChanged methods.  Also key was a change in how the
redraw boolean is determined.
