### ISSUE TITLE
Autotrack median filter incorrectly applied.

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#17]
To reproduce:
- open multi plane file
- auto track on any mass
- click "show temp image" to display image used to compute translations
- Expected behavior, all planes should be medianized before temp image passed to autotrack method.

Plane 1 medianized, plane 2 and higher not:
![image](https://cloud.githubusercontent.com/assets/14008252/16308914/d8b8d156-3934-11e6-9811-d4d86a73c03c.png)
![image](https://cloud.githubusercontent.com/assets/14008252/16308921/de3d06ba-3934-11e6-810a-d1bf4d4e8de7.png)

**Comment by taylorwrt** [comment]
Fixed by running the setSlice method on all slices, not just the current one.
