### ISSUE TITLE
Editing "Image Notes" doesn't trigger saving when saving session.

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#19]
When saving a session a new nrrd file is **not** saved if the image hasn't changed. Right now "change" == operations in MIMSAction that changed pixels. Editing _Image Notes_ (or other operations that would change the header?) should trip "file changed".

**Comment by taylorwrt** [comment]
Fixed.  The changes are:
in imageNotes.java:
    Added document listener to the textArea, and implement the required methods (changedUpdate, removeUpdate, and insertUpdate (which sets the new variable isModified), and added isModified and setIsModified methods.    These allow UI.java to force the update of a mims or nrrd file if its associated notes change.

UI.java
      In the saveSession and saveMIMs methods, added checks to see if the notes text had changed, and if so, allow the saving of the current .im or .nrrd file.
In doInBackground method of FileOpenTask, set the isModified flag of the image notes initially to false so that an unmodified notes area does not force the saving of the current  .im or .nrrd file.
