### ISSUE TITLE
Can't unhide mass images

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#21]
We override the ImagePlus.close() method so when a mass image it's merely hidden and not disposed. Walter noticed that some times these images can't be un-hidden. But I'm having trouble reproducing.

Bug doesn't happen (w/ up to date fiji/openmims):
Ubuntu 14.04
OS X 10.8

**Comment by taylorwrt** [comment]
This bug has been fixed.  I found that this was present in files where multiple windows have the same mass.   The code would hide or show only the first window with a given mass.
