### ISSUE TITLE
Updates to OpenMIMS

### ISSUE THREAD

**Issue by thomasaarholt** [BWHCNI/OpenMIMS#22]
There looks like there have been updates to OpenMIMS that are not available on Fiji's updater. Since I'm on Mac, I only know how to check via Fiji. Does anyone know how I could build and install it from GitHub instead?

**Comment by cpoczatek** [comment]
Hi Thomas,

You don't need to and you can just use Fiji's updater. Change the URL to [http://nrims.partners.org/OpenMIMS-Fiji/](http://nrims.partners.org/OpenMIMS-Fiji/) without the '_stable_' at the end. I think this should "just work", but you might have to remove the OpenMIMS site, restart Fiji, add the new URL.

We haven't done a '_stable_' release in a while and we (I) were waiting to finish migrating to github (done), update the documentation (not done), and maybe move the Fiji update site, before announcing a new version.

That being said, the above URL usually matches the head of the repo, though I was going to update it today. And we'll probably move more of a rolling release in the future.

**Comment by thomasaarholt** [comment]
Brilliant! I'll try it out today! Thanks for an excellent reply (and a nice
plugin!)

**Comment by cpoczatek** [comment]
The [install instructions](https://github.com/BWHCNI/OpenMIMS/wiki/Installation) are now clearer that there are 2 update sites one can use.

**Comment by thomasaarholt** [comment]
Great! Thanks for the help, the biggest difference in this version and the "stable" one, on Mac, is that for some reason the error message setting is set to below "INFO", so I used to get loads of messages in the console. Much better, thanks :D
