### ISSUE TITLE
Opening .im very slow when Fiji is in front [Mac]

### ISSUE THREAD

**Issue by thomasaarholt** [BWHCNI/OpenMIMS#26]
If I drag a .im file into OpenMIMS and immediately switch to a different application, the images are opened very quickly - otherwise each of the images in the .im file will take a long time to open. Does anyone else experience the same? (I've noticed this in Fiji for the past three years - I've just started commenting on GitHub now :) )

edit: By "very slow" I mean something like 30 seconds for a 1.6MB file. If I alt-tab immediately after dropping the file, it is almost instant.

**Comment by cpoczatek** [comment]
What version of OS X are you running? We've noticed similar bugs but maybe not the exact same one.

**Comment by thomasaarholt** [comment]
Running El Capitan (10.11), but I've seen this issue since I started, with 10.8, I think.

**Comment by taylorwrt** [comment]
Thomas,

I also have the problem, as do a lot of other poeple, judging by the discussion here:  http://forum.imagej.net/t/mac-java-speed-issues/304/21

I had this problem on El Capitan, and now on Sierra.   If I read that site correctly, a fix will have to come from the ImageJ people and/or Oracle.

Walter

**Comment by taylorwrt** [comment]
After digging around in various forums, I found a fix for this problem:

Launch Fiji the normal way, then OpenMIMS.   On the Fiji Edit menu, select "Options", then "Misc...", and enable the option "Don't set the Mac menu bar".

This works on the two Macs on which I tried it, both running MacOS 10.12.1 (Sierra).   One is a 2013 Mac Pro and the other a 2013 MacBook Pro.

**Comment by thomasaarholt** [comment]
Well done! Thanks!
