### ISSUE TITLE
Mosaic-Interleaved pb Ratio manager window

### ISSUE THREAD

**Issue by cguillermier** [BWHCNI/OpenMIMS#31]
- Masses wrong attribute
  ![screenshot from 2016-09-07 10-25-57](https://cloud.githubusercontent.com/assets/19674515/18315610/96b80bb8-74e5-11e6-947f-0c28d6e077a6.png)

file:/nrims/data/MIMS_DATA/STEINHAUSER/Cox-Liver-Exp1/mosaic-160823-c7-A1-M5.nrrd

**Comment by taylorwrt** [comment]
This bug was in the interleaveActionPerformed method, and was due to my forgetting to copy the correct mass names and symbols to the newly-created interleaved file.
