### ISSUE TITLE
Window placement in multi-monitor setup

### ISSUE THREAD

**Issue by cathodoluminescence** [BWHCNI/OpenMIMS#4]
Any window opened by OpenMIMS is placed on the primary monitor instead of the monitor where OpenMIMS is running. ImageJ/Fiji is not showing this behaviour.

In a multi-monitor setup it is not very useful to have to move every single window to another screen. Also View > Tile Windows will move all windows back to the primary monitor.
.

**Comment by cpoczatek** [comment]
Thanks for submitting a bug report! A few questions:
- What OS are you using?
- What version of OpenMIMS? If you go to Help -> About OpenMIMS what does the top line say?
- So this doesn't happen with IJ/Fiji itself when opening an image, but does it happen with Fiji -> Window -> Tile or Cascade?

**Comment by cathodoluminescence** [comment]
- Linux/Manjaro, Win8.1
- OpenMIMS v2.5 (rev: 713)
- Ok, I am sorry, maybe I was a bit quick to judge: the 'open dialog' appears correctly on the secondary screen (where Fiji/OpenMIMS is opened), but yes, the image itself also opens then on the primary screen.

I will redirect this issue to the Fiji developers.
