### ISSUE TITLE
segmentation should use ROI groups/tags

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#45]
Instead of using Segmentation->Configure->Classmanager we should rewrite to use some collection of groups and tags in the ROImanager to do the bookkeeping of what ROI is what, eg roi #453 is a training roi for class 'foo'; or roi #678 is a segmentation generated roi for class 'bar'

**Comment by taylorwrt** [comment]
The segmentation classes and RoiManager were changed so that the ROI manager now manages segmentation groups.   The ROI manager now recognizes 3 types of groups:  normal, segmentation, and training, and can manage those groups in the ROI Manager window.
