### ISSUE TITLE
No "add" function in fiji 

### ISSUE THREAD

**Issue by rehemat24** [BWHCNI/OpenMIMS#47]
Hi,
I can't seem to find the "add" function in fiji update - i can only see "add my site" or "add update site" . I'm running Fiji and ImageJ on Windows 10. 
Help??

**Comment by taylorwrt** [comment]
rehemat24,
I am the primary programmer responsible for update to OpenMIMS, at this time.  I need much more detail to understand what you are trying to accomplish.  Please email me directly with details.  E.g., are you trying to update Fiji, or OpenMIMS.   What menu are you using?   Where are you expecting the "Add" item to be, etc.

I do not have a copy of Windows 10 at this time (only Windows 7, Linux, and MacOS), but unless there is evidence that pursuing this problem on Windows 7 is insufficient, I will work with Win 7.
Walter Taylor  (walter.taylor@partners.org).

**Comment by rehemat24** [comment]
Hi Walter,

I’m trying to add the OpenMIMS extension to Fiji. I went to Help then Update Fiji then Manage Update Sites and then in the window that opens after that I was expecting to find the “Add” option but the only options I have are “Add Update Site” and “Add my Site” .

I don’t have access to Windows 7, but if OpenMIMS only works on it I will try to find a computer with it on!

Rehemat

**Comment by taylorwrt** [comment]
Rehemat,

I just downloaded a fresh copy of Fiji and went through this.  Here are the steps.

go to https://fiji.sc/#download https://fiji.sc/#download  and get Fiji
Go to Manage update sites, then click on Add update site button.
In first column, replace New with OpenMIMS.  In the second column, put this:  http://nrims.partners.org/OpenMIMS-Fiji/ http://nrims.partners.org/OpenMIMS-Fiji/
click the  Close button.  You should see a list of the OpenMIMS jar files and other resources.  Click on Apply Changes.
Restart Fiji.  You should now see “Open MIMS Image” on the Plugins menu.   Select it and OpenMIMS should start.
I did this on MacOS, but I don’t think it should be any different on Windows.   Let me know how it goes.

Walter

**Comment by rehemat24** [comment]
Hi Walter,

All working now! Thanks so much for your help.

Rehemat
