### ISSUE TITLE
Renaming default roi group ("...") deletes all ungrouped rois

### ISSUE THREAD

**Issue by agwhitney** [BWHCNI/OpenMIMS#54]
To reproduce: Create some ROIs and move some into a new group. Then rename the default group ("..."), and note that the default group will be emptied. The second group will keep its ROIs.

**Comment by taylorwrt** [comment]
Added a code block to the renameGroupActionPerformed method of MimsRoiManager2.java that warns the user that the default group cannot be renamed, and of course prevents it from being renamed.
