### ISSUE TITLE
Inconsistent ROIs when Zoomed

### ISSUE THREAD

**Issue by agwhitney** [BWHCNI/OpenMIMS#57]
To replicate: Open a .nrrd file and zoom in (problem increases with amount of zoom). Drawing ROIs becomes inconsistent, occasionally drawing them and often not.

I imagine the problem is related to the relation between the image-pixels and how Fiji handles the starting coordinates of an ROI.

**Comment by taylorwrt** [comment]
Previously, as one zoomed in, it got harder and harder for one to create an ROI.  This was  solved (sloppily), by introducing a delay in the mousePressed method of MimsPlus.java.  The delay  is proportional to the level of zoom for an image window.  This problem may have something to do with the time it takes the mouse to traverse very large pixels during a drag.  This delay may prevent the system from thinking the next drag position is in the same pixel as the starting pixel.  A more robust solution might be found in an examination of the mouseMoved method, but this fix should be
sufficient for the major of situations.
