### ISSUE TITLE
Autosave ROIS, review implementation.

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#7]
We should review the autosave ROI feature. They currently get autosaved to system temp which gets clear on reboot. We have several options:
- define a default location in IJ.prefs
- save in working directory as hidden dot files
- make a .openmims hidden directory in the working directory

Not sure which is best...

**Comment by taylorwrt** [comment]
This was changed to function the following way:   First, a checkbox was added to the application preferences to control whether autosaved ROIs are loaded when an image files is loaded.   Autosaved ROIs are saved in a .tmp subdirectory of the directory where the image file is located.  For each .im or nrrd files, up to ten copies of ROI file are kept, with the newest one having the base file name (e.g.,   someFile-im.roi.zip), and older files having a number appended (e.g.  someFile-im(1).rois.zip).      If a .tmp directory does not existing, one is created.   If it exists, but is read-only or not owned by the user, the ROI files are stored in the default Java temporary directory, which differs on OSX, Windows, and Linux.  On OSX, this is a directory in /var/folders  (e.g. /var/folders/_2/6c3ch7n109d_bbt_f59fh6fm0000gn/T/   or something similar.   On Linux, it is /tmp.    On Windows, it is \tmp
When an image file is loaded, the software looks for an ROI file in the tmp directory that is associated with that file and if one is found, a dialog is presented to the user, who can choose to load the ROIS, not load them, or delete all the ROI files in the tmp directory.   If the user chooses to load the ROIS, the software uses the most recent ROI file for that image file.   Nrrd and im files are treated separately.
